{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "10c6314d-eadb-475b-8f44-d334e315a65f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processed: data/genuine/genuine_0.png\n",
      "Processed: data/genuine/genuine_1.png\n",
      "Processed: data/genuine/genuine_10.png\n",
      "Processed: data/genuine/genuine_11.png\n",
      "Processed: data/genuine/genuine_12.png\n",
      "Processed: data/genuine/genuine_13.png\n",
      "Processed: data/genuine/genuine_14.png\n",
      "Processed: data/genuine/genuine_15.png\n",
      "Processed: data/genuine/genuine_16.png\n",
      "Processed: data/genuine/genuine_17.png\n",
      "Processed: data/genuine/genuine_18.png\n",
      "Processed: data/genuine/genuine_19.png\n",
      "Processed: data/genuine/genuine_2.png\n",
      "Processed: data/genuine/genuine_20.png\n",
      "Processed: data/genuine/genuine_21.png\n",
      "Processed: data/genuine/genuine_22.png\n",
      "Processed: data/genuine/genuine_23.png\n",
      "Processed: data/genuine/genuine_24.png\n",
      "Processed: data/genuine/genuine_25.png\n",
      "Processed: data/genuine/genuine_26.png\n",
      "Processed: data/genuine/genuine_27.png\n",
      "Processed: data/genuine/genuine_28.png\n",
      "Processed: data/genuine/genuine_29.png\n",
      "Processed: data/genuine/genuine_3.png\n",
      "Processed: data/genuine/genuine_30.png\n",
      "Processed: data/genuine/genuine_31.png\n",
      "Processed: data/genuine/genuine_32.png\n",
      "Processed: data/genuine/genuine_33.png\n",
      "Processed: data/genuine/genuine_34.png\n",
      "Processed: data/genuine/genuine_35.png\n",
      "Processed: data/genuine/genuine_36.png\n",
      "Processed: data/genuine/genuine_37.png\n",
      "Processed: data/genuine/genuine_38.png\n",
      "Processed: data/genuine/genuine_39.png\n",
      "Processed: data/genuine/genuine_4.png\n",
      "Skipped (blank): data/genuine/genuine_40.png\n",
      "Skipped (blank): data/genuine/genuine_41.png\n",
      "Skipped (blank): data/genuine/genuine_42.png\n",
      "Skipped (blank): data/genuine/genuine_43.png\n",
      "Skipped (blank): data/genuine/genuine_44.png\n",
      "Processed: data/genuine/genuine_45.png\n",
      "Processed: data/genuine/genuine_46.png\n",
      "Processed: data/genuine/genuine_47.png\n",
      "Processed: data/genuine/genuine_48.png\n",
      "Processed: data/genuine/genuine_49.png\n",
      "Processed: data/genuine/genuine_5.png\n",
      "Processed: data/genuine/genuine_50.png\n",
      "Processed: data/genuine/genuine_51.png\n",
      "Processed: data/genuine/genuine_52.png\n",
      "Processed: data/genuine/genuine_53.png\n",
      "Processed: data/genuine/genuine_54.png\n",
      "Processed: data/genuine/genuine_55.png\n",
      "Processed: data/genuine/genuine_56.png\n",
      "Processed: data/genuine/genuine_57.png\n",
      "Processed: data/genuine/genuine_58.png\n",
      "Processed: data/genuine/genuine_59.png\n",
      "Processed: data/genuine/genuine_6.png\n",
      "Processed: data/genuine/genuine_60.png\n",
      "Processed: data/genuine/genuine_61.png\n",
      "Processed: data/genuine/genuine_62.png\n",
      "Processed: data/genuine/genuine_63.png\n",
      "Processed: data/genuine/genuine_64.png\n",
      "Processed: data/genuine/genuine_65.png\n",
      "Processed: data/genuine/genuine_66.png\n",
      "Processed: data/genuine/genuine_67.png\n",
      "Processed: data/genuine/genuine_68.png\n",
      "Skipped (empty crop): data/genuine/genuine_69.png\n",
      "Processed: data/genuine/genuine_7.png\n",
      "Processed: data/genuine/genuine_8.png\n",
      "Processed: data/genuine/genuine_9.png\n",
      "Processed: data/forged/forged_0.png\n",
      "Processed: data/forged/forged_1.png\n",
      "Processed: data/forged/forged_10.png\n",
      "Processed: data/forged/forged_11.png\n",
      "Processed: data/forged/forged_12.png\n",
      "Processed: data/forged/forged_13.png\n",
      "Processed: data/forged/forged_14.png\n",
      "Processed: data/forged/forged_15.png\n",
      "Processed: data/forged/forged_16.png\n",
      "Processed: data/forged/forged_17.png\n",
      "Processed: data/forged/forged_18.png\n",
      "Processed: data/forged/forged_19.png\n",
      "Processed: data/forged/forged_2.png\n",
      "Processed: data/forged/forged_20.png\n",
      "Processed: data/forged/forged_21.png\n",
      "Processed: data/forged/forged_22.png\n",
      "Processed: data/forged/forged_23.png\n",
      "Processed: data/forged/forged_24.png\n",
      "Processed: data/forged/forged_25.png\n",
      "Processed: data/forged/forged_26.png\n",
      "Processed: data/forged/forged_27.png\n",
      "Processed: data/forged/forged_28.png\n",
      "Processed: data/forged/forged_29.png\n",
      "Processed: data/forged/forged_3.png\n",
      "Processed: data/forged/forged_30.png\n",
      "Processed: data/forged/forged_31.png\n",
      "Processed: data/forged/forged_32.png\n",
      "Skipped (empty crop): data/forged/forged_33.png\n",
      "Skipped (blank): data/forged/forged_34.png\n",
      "Skipped (blank): data/forged/forged_35.png\n",
      "Processed: data/forged/forged_36.png\n",
      "Processed: data/forged/forged_37.png\n",
      "Processed: data/forged/forged_38.png\n",
      "Processed: data/forged/forged_39.png\n",
      "Processed: data/forged/forged_4.png\n",
      "Processed: data/forged/forged_40.png\n",
      "Processed: data/forged/forged_41.png\n",
      "Processed: data/forged/forged_42.png\n",
      "Processed: data/forged/forged_43.png\n",
      "Processed: data/forged/forged_44.png\n",
      "Processed: data/forged/forged_45.png\n",
      "Processed: data/forged/forged_46.png\n",
      "Processed: data/forged/forged_47.png\n",
      "Processed: data/forged/forged_48.png\n",
      "Processed: data/forged/forged_49.png\n",
      "Processed: data/forged/forged_5.png\n",
      "Processed: data/forged/forged_50.png\n",
      "Processed: data/forged/forged_51.png\n",
      "Processed: data/forged/forged_52.png\n",
      "Processed: data/forged/forged_53.png\n",
      "Processed: data/forged/forged_6.png\n",
      "Processed: data/forged/forged_7.png\n",
      "Processed: data/forged/forged_8.png\n",
      "Processed: data/forged/forged_9.png\n",
      "All signatures cropped safely\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import os\n",
    "import numpy as np\n",
    "\n",
    "def auto_crop(path):\n",
    "\n",
    "    img = cv2.imread(path,0)\n",
    "\n",
    "    # ⭐ skip if file is not image\n",
    "    if img is None:\n",
    "        print(\"Skipped (not image):\", path)\n",
    "        return\n",
    "\n",
    "    # detect ink\n",
    "    _,thresh = cv2.threshold(img,200,255,cv2.THRESH_BINARY_INV)\n",
    "\n",
    "    coords = np.column_stack(np.where(thresh > 0))\n",
    "\n",
    "    # ⭐ skip blank images\n",
    "    if len(coords) == 0:\n",
    "        print(\"Skipped (blank):\", path)\n",
    "        return\n",
    "\n",
    "    y_min,x_min = coords.min(axis=0)\n",
    "    y_max,x_max = coords.max(axis=0)\n",
    "\n",
    "    cropped = img[y_min:y_max,x_min:x_max]\n",
    "\n",
    "    # ⭐ safety check before resize\n",
    "    if cropped.size == 0:\n",
    "        print(\"Skipped (empty crop):\", path)\n",
    "        return\n",
    "\n",
    "    resized = cv2.resize(cropped,(400,200))\n",
    "\n",
    "    cv2.imwrite(path,resized)\n",
    "    print(\"Processed:\", path)\n",
    "\n",
    "\n",
    "# folders\n",
    "folders = [\"data/genuine\",\"data/forged\"]\n",
    "\n",
    "for folder in folders:\n",
    "    for f in os.listdir(folder):\n",
    "        auto_crop(f\"{folder}/{f}\")\n",
    "\n",
    "print(\"All signatures cropped safely\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
